upstream catalog_backend {
    server catalog-1:8082;
    server catalog-2:8083;
}

server {
    listen 80;
    
    location /auth/ {
        proxy_pass http://auth:8081/;
    }
    
    location /catalog/ {
        proxy_pass http://catalog_backend/;
    }
}